// Generate docs/SIM_REPORT.md: calibration, presets, single-choice levers and
// Maya's "same luck, one choice" pair. Every number in the plan comes from here.
// usage: node sim/report.mjs [N=400]
import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { runMany } from './run.mjs';
import { LIVES, MAYA_BOOK_IT, MAYA_LATER } from './lives.js';
import { SAMPLE_DAYS, runSample, acidRR } from './stephan.js';

const N = +(process.argv[2] || 400);
const node = process.execPath;
const sh = (script, ...args) => execFileSync(node, [new URL(script, import.meta.url).pathname, ...args], { encoding: 'utf8', maxBuffer: 1 << 26 });

const money = v => (v < 0 ? '-$' : '$') + Math.abs(Math.round(v)).toLocaleString('en-US');
const signedMoney = v => (v > 0 ? '+' : '') + money(v);
const signed = v => (v > 0 ? '+' : '') + v;

const presets = [...Object.values(LIVES), MAYA_BOOK_IT, MAYA_LATER].map(p => runMany(p, N));
const calibration = sh('./calibrate.mjs', '3000');
const tmp = new URL('../docs/.levers.json', import.meta.url).pathname;
sh('./levers.mjs', String(Math.min(N, 300)), tmp);
const levers = JSON.parse((await import('node:fs')).readFileSync(tmp, 'utf8'));
(await import('node:fs')).unlinkSync(tmp);
const two = JSON.parse(sh('./twolives.mjs', String(N)));
const hhmm = m => `${Math.floor(m / 60)}h ${String(m % 60).padStart(2, '0')}m`;
const days = SAMPLE_DAYS.map(d => {
  const r = runSample(d);
  return { id: d.id, label: d.label, acidMinutes: r.acidMinutes, sleepAcid: r.sleepAcid, lowest: +r.lowest.toFixed(2), longest: r.longest,
    rr: +acidRR(r.acidDose).toFixed(2), rootMinutes: r.rootMinutes, erosion: Math.round(r.erosion), repairMinutes: r.repairMinutes };
});

let md = `# Simulation report (prototype model v0)

Generated by \`node sim/report.mjs ${N}\`. Deterministic: same code + same seeds = same numbers.
Model: \`sim/model.js\`; parameters with evidence tags: \`sim/params.js\`.

## 1. Calibration against US surveillance data

\`\`\`
${calibration.trim()}
\`\`\`

Known gaps: people who keep their teeth keep ~2-3 more of them at 65+ than today's elders do. Part of this is a
cohort effect (today's 75-year-olds grew up before fluoride toothpaste), so a life born today *should* land
somewhat better, but it needs review with a dental advisor. "Untreated decay" brackets the target depending on
whether early dentin lesions count as cavities.

## 2. Preset lives (${N} lives each)

Dental costs are lifetime out-of-pocket, including what parents paid during childhood.

| Life | Median cost | 90th pct | Teeth lost by 50 / 65 / 80 | Fillings | Root canals | Implants | Pain days | Years hiding smile | Years with gum disease |
|---|---:|---:|---|---:|---:|---:|---:|---:|---:|
${presets.map(r => `| ${r.name} | ${money(r.dentalCostMedian)} | ${money(r.dentalCostP90)} | ${r.missing50} / ${r.missing65} / ${r.missing80} | ${r.fillings} | ${r.rct} | ${r.implants} | ${r.painDays} | ${r.selfConscious} | ${r.gumYears} |`).join('\n')}

## 3. Which single choice matters most? (${levers.N} paired lives, same luck)

Each row changes one thing about a typical life and compares it with the same life (same seed) without the change.

| Choice | Lifetime cost | Teeth lost by 80 | Pain days | Years hiding smile |
|---|---:|---:|---:|---:|
${levers.rows.map(r => `| ${r.lever} | ${signedMoney(r.dCostMean)} | ${signed(r.dMissing80)} | ${signed(r.dPainDays)} | ${signed(r.dSelfConsciousYears)} |`).join('\n')}

## 4. Maya at 34: "Book it" or "Later..." (${two.summary.N} same-luck pairs)

- Median extra cost by 45: **${money(two.summary.medianExtraCostBy45)}** (almost nothing: the bill comes later)
- Median extra cost by 80: **${money(two.summary.medianExtraCostBy80)}**
- Median extra teeth lost by 80: **${two.summary.medianExtraMissingAt80}**
- Share of pairs where "Later..." ends worse: **${Math.round(two.summary.shareWorseBy80 * 100)}%**
- Share where "Later..." is cheaper but costs teeth: **${Math.round(two.summary.shareCheaperButMoreMissing * 100)}%**

Featured pair (seed ${two.featured.seed}, used in the art sample):

| Age | "Book it": spent / teeth lost / pain days | "Later...": spent / teeth lost / pain days |
|---|---|---|
${[34, 45, 62, 79].map(a => { const A = two.featured.snapBookIt[a], B = two.featured.snapLater[a]; return `| ${a} | ${money(A.oop)} / ${A.missing} / ${A.painDays} | ${money(B.oop)} / ${B.missing} / ${B.painDays} |`; }).join('\n')}

"Later..." life, from 34 on: ${two.featured.storyLater.slice(0, 14).join('; ')}.

## 5. The Acid Clock: one day of plaque pH (sim/stephan.js)

A day's meals, snacks and drinks become a 24-hour Stephan curve for a typical mouth. "Acid time" is minutes below
pH 5.5 (enamel dissolves); exposed roots dissolve below ~6.2. Caries pressure is the day's acid dose (area below 5.5)
relative to the first row, before fluoride. Repair time is minutes back above pH 6.0, when enamel regains minerals
(weighted by saliva in the model: repair asleep is slow). Erosion counts acidic drinks bathing the teeth (independent of sugar).

| Day | Acid time | ...of it asleep | Repair time | Lowest pH | Longest stretch | Caries pressure | Below 6.2 (roots) | Erosion |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
${days.map(d => `| ${d.label} | ${hhmm(d.acidMinutes)} | ${d.sleepAcid ? hhmm(d.sleepAcid) : '-'} | ${hhmm(d.repairMinutes)} | ${d.lowest.toFixed(2)} | ${d.longest} min | x${d.rr.toFixed(2)} | ${hhmm(d.rootMinutes)} | ${d.erosion || '-'} |`).join('\n')}

## 6. The Acid Clock across a life (${N} lives each)

Average minutes a day below pH 5.5 in each stage of life (the day changes as habits, job, bacteria, plaque and
saliva change), and minutes below 6.2 once roots are exposed.

| Life | Toddler (2-3) | Kid (6-12) | Teen (13-17) | Working (25-55) | Retired (66-79) | Roots, retired |
|---|---:|---:|---:|---:|---:|---:|
${presets.map(r => `| ${r.name} | ${r.acid.toddler} | ${r.acid.kid} | ${r.acid.teen} | ${r.acid.adult} | ${r.acid.elder} | ${r.acid.elderRoot} |`).join('\n')}
`;
writeFileSync(new URL('../docs/SIM_REPORT.md', import.meta.url), md);
writeFileSync(new URL('../docs/sim-report.json', import.meta.url), JSON.stringify({ N, presets, levers, two, acid: { days } }, null, 2));
console.log(md);
