// People: front-facing chibi paper dolls.
// A person = back hair? + body (age/outfit) + arms (pose) + head (hair style)
//          + face (expression) + props. Colors are roles (see CHAR_KEY) so any
// sprite can take any skin tone, hair color or outfit palette.
import { sprite } from '../lib/pix.js';

// ---------------------------------------------------------------------------
// ADULT HEADS (16 wide). Bottom row = jaw. Face overlay is placed at
// (x+3, y+h-6): eyebrow row, 2 eye rows, blush row, mouth row, jaw row.

export const HEAD = {};

HEAD.short = sprite(`
.....oooooo.....
...oohhhhhhoo...
..ohhhhhhhhhho..
.ohhiihhhhhhhHo.
.ohiihhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhhshhhhshhHo.
.ohssssssssssHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

HEAD.bun = sprite(`
......oooo......
.....ohhiHo.....
.....ohhhHo.....
.....ooHHoo.....
...oohhhhhhoo...
..ohhhhhhhhhho..
.ohhiihhhhhhhHo.
.ohiihhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhhhhhhsshhHo.
.ohhhssssssssHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

HEAD.bob = sprite(`
.....oooooo.....
...oohhhhhhoo...
..ohhhhhhhhhho..
.ohhiihhhhhhhHo.
.ohiihhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhssssssssHHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohssssssssSSHo.
.ohosssssssSoHo.
.oo.osssssSo.oo.
`);

HEAD.curly = sprite(`
....oo.oo.oo....
..oohhohhohhoo..
.ohhihhhhhhhhhho
.ohiihhhhhhhhHHo
ohhiihhhhhhhhhHo
ohhhhhhhhhhhhhHo
ohhhhshhshhshhHo
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

HEAD.buzz = sprite(`
................
.....oooooo.....
...ooHhhhhHoo...
..oHhhhhhhhhHo..
.oHhhhhhhhhhhHo.
.ohsssssssssSHo.
.osssssssssssSo.
.osssssssssssSo.
.osssssssssssSo.
.osssssssssssSo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);


HEAD.long = sprite(`
.....oooooo.....
...oohhhhhhoo...
..ohhhhhhhhhho..
.ohhiihhhhhhhHo.
.ohiihhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhssssssssHHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohssssssssSSHo.
.ohosssssssSoHo.
.ohhosssssSohHo.
`);

// Long hair that falls behind the shoulders (drawn before the body).
export const BACK = {};
BACK.long = sprite(`
................
................
................
................
................
................
................
................
................
................
................
................
.ohh........hHo.
.ohh........hHo.
.ohho......ohHo.
.ohho......ohHo.
..oo........oo..
`);

HEAD.pigtails = sprite(`
.....oooooo.....
...oohhhhhhoo...
..ohhhhhhhhhho..
oohhiihhhhhhhHoo
ohohiihhhhhhhHoH
ohohhhhhhhhhhHoH
oohhhhhhhhhhhHoo
.ohhssssssssHHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

HEAD.spiky = sprite(`
...o..o..o......
..oho.oho.ohoo..
..ohhohhhohhHo..
.ohhiihhhhhhhHo.
.ohiihhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohhhshhhshhhHo.
.ohssssssssssHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

HEAD.balding = sprite(`
................
.....oooooo.....
...oollsssSoo...
..olsssssssSSo..
.ohlssssssssSHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

HEAD.curlyShort = sprite(`
................
....oo.oo.oo....
...ohhohhohhoo..
..ohiihhhhhhHo..
.ohhihhhhhhhhHo.
.ohhhhhhhhhhhHo.
.ohshhshhshhsHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
.ohsssssssssSHo.
..ossssssssSSo..
..osssssssssSo..
...osssssssSo...
`);

// Toddler / baby heads (10 wide). Face overlay: FACE_SMALL at (x+4, y+h-6).
HEAD.toddler = sprite(`
......oo........
.....ohho.......
....oohhHoo.....
...ohhhhhhHo....
...ohhshhshHo...
...osssssssSo...
...osssssssSo...
...osssssssSo...
...osssssssSo...
....ossssssSo...
.....oooooo.....
`);

HEAD.baby = sprite(`
.......oo.......
......oho.......
.....oooooo.....
....olssssSo....
...osssssssSo...
...osssssssSo...
...osssssssSo...
...osssssssSo...
....ossssssSo...
.....oooooo.....
`);

// ---------------------------------------------------------------------------
// FACES (10x6 overlays). Columns map to head cols 3..12.
// eye columns: 2 and 7; blush: 1 and 8; mouth: 4-5.

export const FACE = {
  neutral: sprite(`
..........
..e....e..
..e....e..
.b......b.
....mm....
..........
`),
  smile: sprite(`
..........
..e....e..
..e....e..
.b......b.
...m..m...
....mm....
`),
  grin: sprite(`
..........
..e....e..
.e.e..e.e.
.b......b.
...mwwm...
....nn....
`),
  wince: sprite(`
.e......e.
..e....e..
.e......e.
.b......b.
...m.mm...
....m.....
`),
  sleep: sprite(`
..........
..........
..ee..ee..
.b......b.
.....m....
..........
`),
  worried: sprite(`
...e..e...
..e....e..
..e....e..
.b......b.
...mmm....
......m...
`),
  sad: sprite(`
...e..e...
..e....e..
..e....e..
.b......b.
....mm....
...m..m...
`),
  surprised: sprite(`
..........
..e....e..
..e....e..
.b......b.
....mm....
....mm....
`),
  clench: sprite(`
.ee....ee.
...e..e...
..e....e..
.b......b.
...mwwm...
...mmmm...
`),
  content: sprite(`
..........
..........
.e.e..e.e.
.b......b.
...m..m...
....mm....
`),
};


// Small faces for toddlers/babies (8 wide, mapped to head cols 4..11; eyes 6 & 9).
export const FACE_SMALL = {
  neutral: sprite(`
........
..e..e..
..e..e..
.b....b.
...mm...
........
`),
  smile: sprite(`
........
..e..e..
..e..e..
.b....b.
..m..m..
...mm...
`),
  happy: sprite(`
........
..e..e..
.e.ee.e.
.b....b.
...mm...
...nn...
`),
  cry: sprite(`
........
.ee..ee.
..w..w..
.bw..wb.
...mm...
...mm...
`),
  sleep: sprite(`
........
........
.ee..ee.
.b....b.
...m....
........
`),
};

// Glasses overlay, same footprint as FACE (10x6).
export const GLASSES = sprite(`
..........
.TTT..TTT.
.T.TTTT.T.
.TTT..TTT.
..........
..........
`, { T: 'stone' });

// ---------------------------------------------------------------------------
// ADULT BODY (torso + legs, no arms). Placed so row 0 sits right under the jaw.

export const BODY = {};

BODY.tee = sprite(`
..ocooooooooco..
..occcccccccCo..
..odcccccccCCo..
..odcccccccCCo..
..occccccccCCo..
..occccccccCCo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);


BODY.shirtTie = sprite(`
..ocooooooooco..
..occcuxxucccCo.
..odcccxXccCCo..
..odcccxXccCCo..
..occccxXccCCo..
..occccccccCCo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.apron = sprite(`
..ocooooooooco..
..occuccccuCCo..
..odcuuuuuuCCo..
..odcuuuuuuCCo..
..occuuUUuuCCo..
..ouuuuuuuuUUo..
...ouuuuuuuUo...
....ouuuuuUo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.scrubs = sprite(`
..ocooooooooco..
..occccsscccCo..
..odkccccccCCo..
..odcccccccCCo..
..occccccccCCo..
..occccccccCCo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.vest = sprite(`
..oxooooooooxo..
..oxxxccccxXXo..
..oxxxccccxXXo..
..oxxxccccxXXo..
..ouuuccccuUUo..
..oxxxccccxXXo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.jersey = sprite(`
..ocooooooooco..
..occccccccCCo..
..ouuuuuuuuUUo..
..occccccccCCo..
..occccccccCCo..
..ouuuuuuuuUUo..
...opppppppPo...
....opppppPo....
....oxxooxXo....
....oxxooxXo....
...offfoofffo...
....ttt..ttt....
`);

BODY.cardigan = sprite(`
..oxooooooooxo..
..oxxcccccxXXo..
..oxxcccccxXXo..
..oxxccccxxXXo..
..oxxxcccxxXXo..
..oxxxcccxxXXo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.hoodie = sprite(`
..oCooooooooCo..
..oCccuccuccCo..
..odccuccuCCCo..
..odcccccccCCo..
..occCCCCCcCCo..
..occccccccCCo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.skirt = sprite(`
..ocooooooooco..
..occcccccccCo..
..odcccccccCCo..
..odcccccccCCo..
..occccccccCCo..
..occccccccCCo..
...opppppppPo...
..opppppppppPo..
..oooooooooooo..
....osSoosSo....
...offfoofffo...
....ooo..ooo....
`);

// Teen: one torso row shorter than adult.
BODY.teen = sprite(`
..ocooooooooco..
..occcccccccCo..
..odcccccccCCo..
..occccccccCCo..
..occccccccCCo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

BODY.teenHoodie = sprite(`
..oCooooooooCo..
..oCccuccuccCo..
..odccuccuCCCo..
..occCCCCCcCCo..
..occccccccCCo..
...opppppppPo...
....opppppPo....
....oppoopPo....
....oppoopPo....
...offfoofffo...
....ooo..ooo....
`);

// Kid: narrower torso (arms tucked inside the outline), shorts.
BODY.kid = sprite(`
...oooooooooo...
...occcccccCo...
...odccccCCCo...
...occccccCCo...
...opppppppPo...
....osSoosSo....
...offfoofffo...
....ooo..ooo....
`);

BODY.kidDress = sprite(`
...oooooooooo...
...occcccccCo...
...odccccCCCo...
..occcccccccCo..
..oooooooooooo..
....osSoosSo....
...offfoofffo...
....ooo..ooo....
`);

// Toddler (age ~2): tiny overalls.
BODY.toddler = sprite(`
....occcccCo....
...oscpcpcCSo...
....opppppPo....
....oppooPPo....
....offoofFo....
.....oo..oo.....
`);

// Baby sitting: onesie, feet splayed forward.
BODY.baby = sprite(`
....occcccCo....
...osccccccSo...
..oocccccccCoo..
.offoooooooooffo
..oo........oo..
`);

// ---------------------------------------------------------------------------
// ADULT ARMS (overlays on the body, same origin as BODY).

export const ARMS = {};

ARMS.down = sprite(`
................
................
....C......C....
....C......C....
...sC......CS...
...sC......CS...
..oso......oSo..
...o........o...
`);

// ---------------------------------------------------------------------------
// Compose a person. (x, footY): left edge of the 16px frame, row under the feet.
// spec: { head, face, body, arms, look, flip, props: [{ spr, dx, dy }] }
export function drawPerson(pix, x, footY, spec) {
  const head = typeof spec.head === 'string' ? HEAD[spec.head] : spec.head;
  const body = typeof spec.body === 'string' ? BODY[spec.body] : spec.body;
  const arms = spec.arms === null ? null : typeof spec.arms === 'object' ? spec.arms : ARMS[spec.arms || 'down'];
  const small = head && head.w === 16 && (spec.head === 'toddler' || spec.head === 'baby');
  const face = typeof spec.face === 'string' ? (small ? FACE_SMALL[spec.face] : FACE[spec.face]) : spec.face;
  const o = { look: spec.look, flip: spec.flip };
  const by = footY - body.h;
  const hy = by - head.h;
  if (spec.back) pix.sprite(typeof spec.back === 'string' ? BACK[spec.back] : spec.back, x, hy, o);
  pix.sprite(body, x, by, o);
  const armsOver = arms && (spec.armsOver ?? arms.over);
  if (arms && !armsOver) pix.sprite(arms, x, by - (arms.oy || 0), o);
  pix.sprite(head, x, hy, o);
  if (face) pix.sprite(face, x + (face.w === 8 ? 4 : 3), hy + head.h - 6, o);
  if (spec.glasses) pix.sprite(GLASSES, x + 3, hy + head.h - 6, o);
  if (spec.hat) {
    const hat = typeof spec.hat === 'string' ? HAT[spec.hat] : spec.hat;
    pix.sprite(hat, x, hy + head.h - 7 - hat.h + (spec.hatDrop || 0), o);
  }
  if (arms && armsOver) pix.sprite(arms, x, by - (arms.oy || 0), o);
  for (const p of spec.props || []) pix.sprite(p.spr, x + p.dx, by + p.dy, { look: p.look || spec.look, flip: p.flip });
  for (const p of spec.after || []) pix.sprite(p.spr, x + p.dx, by + p.dy, { look: p.look || spec.look, flip: p.flip });
  return { headY: hy, bodyY: by };
}

// Right hand on right cheek (toothache), left arm down.
ARMS.cheek = sprite(`
...........osso.
...........osSo.
............osSo
............osSo
............ocCo
............ocCo
....C.........o.
....C...........
...sC...........
...sC...........
..oso...........
...o............
`, {}, { oy: 4, over: true });

// Hand over mouth (embarrassed laugh / hiding smile), right arm down.
ARMS.cover = sprite(`
......oooo......
.....osssso.....
.....oSssSo.....
......osSo......
......osSo......
.....ocCo...C...
....ocCo....C...
...ocCo.....CS..
....oo......CS..
............oSo.
.............o..
`, {}, { oy: 3, over: true });

// Both hands in front at chest height (holding a mug, phone, cupcake...).
ARMS.hold = sprite(`
................
................
....C......C....
...sC......CS...
...sss....ssS...
...ooo....ooo...
`, {}, { over: true });

// Arms wrapped around a big box (heavy lifting).
ARMS.carry = sprite(`
................
..oooooooooooo..
.oyyyyyXXyyyyyo.
.oxxxxxXXxxxxxo.
osoxxxxXXxxxxoSo
osoxxxxxxxxxxoSo
.ooxxxxxxxxxxoo.
..oxxxxxxxxxxo..
..oXxxxxxxxxXo..
..oooooooooooo..
`, { x: 'wood3', X: 'wood2', y: 'wood4' }, { over: true });

// Right arm waving above the head.
ARMS.wave = sprite(`
............osso
............osSo
............osSo
...........osSo.
...........osSo.
...........osSo.
...........ocCo.
...........ocCo.
....C......oCo..
....C...........
...sC...........
...sC...........
..oso...........
...o............
`, {}, { oy: 6, over: true });


ARMS.teen = sprite(`
................
................
....C......C....
...sC......CS...
...sC......CS...
..oso......oSo..
...o........o...
`);

ARMS.kid = sprite(`
................
.....C....C.....
....sC....CS....
...oso....oSo...
....o......o....
`);

// Kid brushing: toothbrush in the mouth, right hand holding the handle.
ARMS.kidBrush = sprite(`
..........osso..
.......wwxxsSo..
..........osSo..
...........oSo..
.....C..........
....sC..........
...oso..........
....o...........
`, { x: 'teal2', w: 'white' }, { oy: 3, over: true });

// Kid holding a balloon string up in the right hand.
ARMS.kidBalloon = sprite(`
............o...
...........oso..
.....C.....oSo..
....sC.....oCo..
...oso......o...
....o...........
`, {}, { oy: 1, over: true });

// Toddler holding a sippy cup (hands are part of the toddler body).
// Long sleeves (sweaters, cardigans, office shirts).
ARMS.sleeves = sprite(`
................
................
....C......C....
....C......C....
...cC......CC...
...cC......CC...
..oso......oSo..
...o........o...
`);

// Holding a cane in the right hand (senior).
ARMS.cane = sprite(`
................
................
....C......C....
....C......C....
...cC......CC...
...cC......CCoo.
..oso......oSoxo
...o........oxo.
.............xo.
.............xo.
.............xo.
.............xo.
.............oo.
`, { x: 'wood2' });

// Sleeves variant helper: turn a tee arm set into long sleeves by mapping skin->top.
export function longSleeves(arms) {
  return { ...arms, key: { ...arms.key, s: 'top.1', S: 'top.0' } };
}

export const HAT = {};

// Hats are drawn so their bottom row lands on the hairline (see drawPerson).
HAT.chef = sprite(`
....oo.oo.oo....
...okkokkokko...
..okkkkkkkkkKo..
..okkkkkkkkkKo..
...okkkkkkkKo...
...oKKKKKKKKo...
...okkkkkkkKo...
..oooooooooooo..
`);

HAT.hardhat = sprite(`
.....oooooo.....
...ooxxyxxxoo...
..oxxxyxxxxxXo..
..oxxxxxxxxxXo..
.oooooooooooooo.
`, { x: 'gold2', X: 'gold1', y: 'gold3' });

HAT.helmet = sprite(`
.....oooooo.....
...ooxxxxxxoo...
..oxyyxxxxxxXo..
.oxyxxkkkxxxXXo.
.oxxxxxxxxxxXXo.
.ooooxxxxxxoooo.
.oTo........oTo.
.oTTTTTTTTTTTTo.
`, { x: 'acc.1', X: 'acc.0', y: 'acc.2', k: 'white', T: 'mist' });

HAT.cap = sprite(`
.....oooooo.....
...ooxxxxxxoo...
..oxxyxxxxxxXo..
..oxxxxxxxxxXo..
..ooooooooooooo.
.........oxxxxo.
.........oooooo.
`);
